
export const dbChatbox = [
    {
      id: 1,
      sender: "John Davidson",
      lastMessage: "Hey! How have you been?",
      unreadMessages: 2,
      time: "03:42",
      date: "2025-06-20",
      online: true,
      profile: "https://images.unsplash.com/photo-1499714608240-22fc6ad53fb2?auto=format&fit=crop&w=500&q=60",
    },
    {
      id: 2,
      sender: "Frank Jackson",
      lastMessage: "Let’s move the meeting to this week",
      unreadMessages: 2,
      time: "03:45",
      date: "2025-06-19",
      online: false,
      profile: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    {
      id: 3,
      sender: "Angela Yu",
      lastMessage: "Sent you the files, let me know",
      unreadMessages: 0,
      time: "03:47",
      date: "2025-06-19",
      online: true,
      profile: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    {
      id: 4,
      sender: "Michael Chen",
      lastMessage: "Let’s grab lunch tomorrow?",
      unreadMessages: 1,
      time: "03:50",
      date: "2025-06-18",
      online: false,
      profile: "https://randomuser.me/api/portraits/men/45.jpg",
    },
    {
      id: 5,
      sender: "Sophia Liu",
      lastMessage: "Haha that was hilarious 😂",
      unreadMessages: 0,
      time: "03:55",
      date: "2025-06-18",
      online: true,
      profile: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    {
      id: 6,
      sender: "David Kim",
      lastMessage: "See you at the gym later?",
      unreadMessages: 3,
      time: "04:00",
      date: "2025-06-17",
      online: true,
      profile: "https://randomuser.me/api/portraits/men/78.jpg",
    },
    {
      id: 7,
      sender: "Emily Stone",
      lastMessage: "Thanks! Appreciate the help!",
      unreadMessages: 0,
      time: "04:02",
      date: "2025-06-17",
      online: false,
      profile: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    {
      id: 8,
      sender: "Chris Evans",
      lastMessage: "Gimme 5 mins, almost done.",
      unreadMessages: 1,
      time: "04:04",
      date: "2025-06-16",
      online: false,
      profile: "https://randomuser.me/api/portraits/men/80.jpg",
    },
    {
      id: 9,
      sender: "Nina Hart",
      lastMessage: "Can't talk right now, call u later.",
      unreadMessages: 6,
      time: "04:10",
      date: "2025-06-15",
      online: true,
      profile: "https://randomuser.me/api/portraits/women/18.jpg",
    },
    {
      id: 10,
      sender: "Brian Lee",
      lastMessage: "Got the tickets. We’re set!",
      unreadMessages: 0,
      time: "04:15",
      date: "2025-06-14",
      online: true,
      profile: "https://randomuser.me/api/portraits/men/14.jpg",
    },
];  